'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace FriendsService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PartnersSoap", [Namespace]:="http://www.apress.com/services/friendsreunion")>  _
    Public Class Partners
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/FriendsReunion/Services/Partners.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/services/friendsreunion/GetAttendees", RequestNamespace:="http://www.apress.com/services/friendsreunion", ResponseNamespace:="http://www.apress.com/services/friendsreunion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAttendees(ByVal placeId As String) As Integer
            Dim results() As Object = Me.Invoke("GetAttendees", New Object() {placeId})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginGetAttendees(ByVal placeId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAttendees", New Object() {placeId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAttendees(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/services/friendsreunion/GetContactRequests", RequestNamespace:="http://www.apress.com/services/friendsreunion", ResponseNamespace:="http://www.apress.com/services/friendsreunion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetContactRequests(ByVal login As String, ByVal password As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("GetContactRequests", New Object() {login, password})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGetContactRequests(ByVal login As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetContactRequests", New Object() {login, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetContactRequests(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/services/friendsreunion/GetContactRequestsCustom", RequestNamespace:="http://www.apress.com/services/friendsreunion", ResponseNamespace:="http://www.apress.com/services/friendsreunion", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetContactRequestsCustom(ByVal login As String, ByVal password As String) As Contact()
            Dim results() As Object = Me.Invoke("GetContactRequestsCustom", New Object() {login, password})
            Return CType(results(0),Contact())
        End Function
        
        '<remarks/>
        Public Function BeginGetContactRequestsCustom(ByVal login As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetContactRequestsCustom", New Object() {login, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetContactRequestsCustom(ByVal asyncResult As System.IAsyncResult) As Contact()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Contact())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.apress.com/services/friendsreunion")>  _
    Public Class Contact
        
        '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property FirstName() As String
      Get
        Return FirstNamefield
      End Get
      Set(ByVal Value As String)
        FirstNamefield = Value
      End Set
    End Property
    Dim FirstNamefield As String

    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property LastName() As String
      Get
        Return LastNamefield
      End Get
      Set(ByVal Value As String)
        LastNamefield = Value
      End Set
    End Property
    Dim LastNamefield As String

    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Email() As String
      Get
        Return Emailfield
      End Get
      Set(ByVal Value As String)
        Emailfield = Value
      End Set
    End Property
    Dim Emailfield As String

    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Notes() As String
      Get
        Return Notesfield
      End Get
      Set(ByVal Value As String)
        Notesfield = Value
      End Set
    End Property
    Dim Notesfield As String

    '<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property IsApproved() As Boolean
      Get
        Return IsApprovedfield
      End Get
      Set(ByVal Value As Boolean)
        IsApprovedfield = Value
      End Set
    End Property
    Dim IsApprovedfield As Boolean
  End Class
End Namespace